version: '3.1'

services:
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - "./containers-dev/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER:-blog}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123}"
      - "POSTGRES_DB=${POSTGRES_DB:-blog}"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080